### ISSUE TITLE
Extension desynced from release

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox-demo#1]
https://github.com/libriscv/godot-sandbox/releases/tag/v0.11

**Comment by fire** [comment]
Apply 

```
docker stop godot-cpp-compiler
docker rm godot-cpp-compiler
docker pull ghcr.io/libriscv/cpp_compiler
docker pull ghcr.io/libriscv/rust_compiler
```

from https://github.com/libriscv/godot-sandbox/issues/66

**Comment by fire** [comment]
![editor_screenshot_2024-08-30T081406](https://github.com/user-attachments/assets/d1b136ca-e3e7-43a7-a4b5-9efff3316d83)

**Comment by fire** [comment]
The container doesn't seem to start.

**Comment by fire** [comment]
Must navigate to each Rust or C++ script and hit save.

**Comment by fire** [comment]
platform is required for the macos.

```bash
docker pull --platform linux/amd64 ghcr.io/libriscv/cpp_compiler
docker pull --platform linux/amd64 ghcr.io/libriscv/rust_compiler
```

Edited:

the images are amd64, the platform is arm64.

**Comment by fire** [comment]
> I thought we built ARM images now?

We do not. @Ughuuu

**Comment by Ughuuu** [comment]
Well unrelated to this repo anyway, as images are built on other repo.

**Comment by Ughuuu** [comment]
This PR will add more arch, aparently forgot to set the platforms option: https://github.com/libriscv/godot-sandbox/pull/79

**Comment by fire** [comment]
Thanks
