### ISSUE TITLE
Update the sandbox to use v0.21

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox-demo#11]
https://github.com/libriscv/godot-sandbox/releases/tag/v0.21

Currently linking to https://ifiregames.itch.io/godot-sandbox-demo

**Comment by fwsGonzo** [comment]
This should be v0.22 now, and I am on it.

**Comment by fire** [comment]
Does not seemed to be merged into master.

https://github.com/libriscv/godot-sandbox-demo
