### ISSUE TITLE
Had to unblock windows dlls

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox-demo#2]
:(

**Comment by fwsGonzo** [comment]
This one I don't quite understand. Did the Windows Defender trigger on the .dlls?

**Comment by fire** [comment]
Windows Defender did not trigger. Windows required me to click unblock.

**Comment by fire** [comment]
https://www.tenforums.com/tutorials/5357-unblock-file-windows-10-a.html

**Comment by fire** [comment]
Nothing we can do really.

We can apply for a certificate or pay 400 usd.
