### ISSUE TITLE
Prints are broken on Windows

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox-demo#3]
![editor_screenshot_2024-08-30T083706](https://github.com/user-attachments/assets/28fcf532-c81a-45dc-9d85-eae27a57983f)

**Comment by fire** [comment]
```
[0m
```
Weird words.

**Comment by fwsGonzo** [comment]
Fixed by disabling the unfiltered version. I think there's a difference where the yellow warning-prints always show last on Linux, however if the red text shows last on any platform, it might appear unreadable.
