### ISSUE TITLE
Must navigate to each Rust or C++ script and hit save.

### ISSUE THREAD

**Issue by fire** [libriscv/godot-sandbox-demo#5]
When upgrading godot-sandbox the scripts don't know how to upgrade themselves.

**Comment by fwsGonzo** [comment]
We will figure out something for this. You are right, it shouldn't be this way.

**Comment by fire** [comment]
Observed behaviour:

When riscv elf scripts fail to compile they keep the last compiled version. Contrast with gdscript behaviour where scripts are **always** "recompiled" and if they fail, they fail.

**Comment by fire** [comment]
Should be fixed in recent release.
